### PR TITLE
More refactoring

### PR DESCRIPTION
**Pull request by bonzini**
Please review and pull my simplifications. About 800 lines of code are moved from the "reference implementation" to generic code, yay! :)

### CODE REVIEW

**Review by jiangliu — COMMENTED** [review]
Hi Paolo,
        I have some question about this changeset when review it again. 
       Per my understanding, this changeset tries to support the corner case of accessing the last byte of the address space. Is that right? If so, the "total == count" check at line 213 should have covered such a case.
       Otherwise if it's to support real wrapping around, what's the usage cases to read some data at the end and then continue at the beginning of the address space? It smells like a bug:)

**Comment by bonzini** [comment]
I assume you're talking about "allow accesses to wrap around to the beginning of the address space" (commit [3c6831c2](https://github.com/jiangliu/memory-model/pull/1/commits/3c6831c20a27dd6e1df2ca78c199c3f4f322320f).

>  Otherwise if it's to support real wrapping around, what's the usage cases to read some data at the end and then continue at the beginning of the address space? It smells like a bug:)

It's for real wrapping around. It is usually valid according to the spec for a driver to ask for DMA of 0x2_0000 bytes starting at 0xFFFF_FFFF_FFFF_0000. The device will then read from 0xF...0000 o to 0xF...FFFF and from 0x0 to 0xFFFF.

I agree that it's not something that is usually _desired_, but if the specs allow it we have to support it.

**Comment by jiangliu** [comment]
> On Feb 27, 2019, at 8:49 PM, Paolo Bonzini <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> I assume you're talking about "allow accesses to wrap around to the beginning of the address space" (commit 3c6831c2 <https://github.com/jiangliu/memory-model/pull/1/commits/3c6831c20a27dd6e1df2ca78c199c3f4f322320f>.
> 
> Otherwise if it's to support real wrapping around, what's the usage cases to read some data at the end and then continue at the beginning of the address space? It smells like a bug:)
> 
> It's for real wrapping around. It is usually valid according to the spec for a driver to ask for DMA of 0x2_0000 bytes starting at 0xFFFF_FFFF_FFFF_0000. The device will then read from 0xF...0000 o to 0xF...FFFF and from 0x0 to 0xFFFF.
> 
> I agree that it's not something that is usually desired, but if the specs allow it we have to support it.
> 
Thanks for the information. Previous I only know IO port at 0xffff needs special handling, haven’t noticed that DMA controllers have the same behavior too.

I have done some cleanup based on your commits and push them to my personal repository.
Should we go to create rust-vmm/vm-memory repository and send PR for merging?

BTW sorry for the inconvenience,  I used to do code review by email and still learning how to do code review by GitHub :(

**Comment by bonzini** [comment]
Yes, please go ahead! I left a couple comments but that's it. You probably should also do a final commit to rename the crate from memory-model to vm-memory.

> BTW sorry for the inconvenience, I used to do code review by email and still learning how to do code review by GitHub :(

Same here! :D

**Pull request merged**
